function makeSeedData() {
  const base = new Date("2026-05-12T00:00:00.000Z");
  const at = (minutes) => new Date(base.getTime() + minutes * 60 * 1000).toISOString();

  const tasks = [
    {
      id: "TASK-1001",
      title: "논문 임베딩 파이프라인 스펙 작성",
      origin: "arxiv:2605.01234",
      stage: "spec",
      status: "active",
      priority: "high",
      relatedModules: ["backend/research_parser", "backend/task_generator"],
      linkedResearch: ["PAPER-100"],
      acceptanceCriteria: [
        "입력/출력 스키마가 명시되어야 한다",
        "오류 처리 전략이 포함되어야 한다",
      ],
      createdAt: at(5),
      updatedAt: at(30),
      ownerAgent: "Hermes",
    },
    {
      id: "TASK-1002",
      title: "태스크 우선순위 산정 로직 구현",
      origin: "arxiv:2605.09121",
      stage: "build",
      status: "active",
      priority: "urgent",
      relatedModules: ["backend/task_generator", "backend/scoring"],
      linkedResearch: ["PAPER-101"],
      acceptanceCriteria: [
        "우선순위 점수가 0~100으로 계산되어야 한다",
        "테스트 케이스 5개 이상 통과",
      ],
      createdAt: at(20),
      updatedAt: at(210),
      ownerAgent: "OpenCode",
    },
    {
      id: "TASK-1003",
      title: "PR 품질 게이트 정책 반영",
      origin: "manual:quality-policy-v3",
      stage: "review",
      status: "blocked",
      priority: "medium",
      relatedModules: ["backend/review_agent", "github/integration"],
      linkedResearch: ["DOC-REVIEW-03"],
      acceptanceCriteria: [
        "보안/성능/테스트 커버리지 룰 적용",
        "차단 사유가 이벤트 로그에 기록",
      ],
      createdAt: at(40),
      updatedAt: at(315),
      ownerAgent: "CodeRabbit",
    },
    {
      id: "TASK-1004",
      title: "연구-태스크-PR 링크 시각화",
      origin: "openalex:W44099123",
      stage: "ship",
      status: "active",
      priority: "high",
      relatedModules: ["frontend/knowledge_flow", "backend/graph_api"],
      linkedResearch: ["PAPER-102"],
      acceptanceCriteria: [
        "연결 그래프에서 출처 추적 가능",
        "PR 상세와 양방향 링크",
      ],
      createdAt: at(70),
      updatedAt: at(420),
      ownerAgent: "Codex",
    },
    {
      id: "TASK-1005",
      title: "빌드 실패 재시도 정책 개선",
      origin: "incident:INC-8821",
      stage: "failed",
      status: "failed",
      priority: "urgent",
      relatedModules: ["backend/orchestrator", "backend/retry_policy"],
      linkedResearch: ["INCIDENT-8821"],
      acceptanceCriteria: ["최대 3회 재시도", "지수 백오프 적용"],
      createdAt: at(80),
      updatedAt: at(510),
      ownerAgent: "Hermes",
    },
  ];

  const runs = [
    {
      id: "RUN-9001",
      taskId: "TASK-1001",
      agentName: "Hermes",
      stage: "spec",
      status: "running",
      startedAt: at(24),
      finishedAt: null,
      retryCount: 0,
      tokenUsage: 10234,
      costUsd: 0.072,
      outcome: "스펙 초안 작성 중",
      logSummary: "연구 요약을 스펙 템플릿에 매핑 중",
    },
    {
      id: "RUN-9002",
      taskId: "TASK-1002",
      agentName: "OpenCode",
      stage: "build",
      status: "running",
      startedAt: at(180),
      finishedAt: null,
      retryCount: 1,
      tokenUsage: 28341,
      costUsd: 0.194,
      outcome: "점수 함수 리팩터링 진행",
      logSummary: "가중치 캘리브레이션 로직 업데이트",
    },
    {
      id: "RUN-9003",
      taskId: "TASK-1003",
      agentName: "CodeRabbit",
      stage: "review",
      status: "failed",
      startedAt: at(280),
      finishedAt: at(300),
      retryCount: 0,
      tokenUsage: 9440,
      costUsd: 0.053,
      outcome: "테스트 커버리지 기준 미달",
      logSummary: "Critical 체크 실패로 차단",
    },
    {
      id: "RUN-9004",
      taskId: "TASK-1004",
      agentName: "Codex",
      stage: "ship",
      status: "success",
      startedAt: at(390),
      finishedAt: at(430),
      retryCount: 0,
      tokenUsage: 18764,
      costUsd: 0.111,
      outcome: "머지 준비 완료",
      logSummary: "릴리스 노트 및 머지 체크리스트 생성",
    },
  ];

  const events = [
    {
      id: "EVT-7001",
      taskId: "TASK-1001",
      runId: "RUN-9001",
      timestamp: at(25),
      stage: "spec",
      type: "info",
      severity: "low",
      message: "연구 요약 추출 완료",
      relatedFiles: ["research_parser.py"],
      relatedTests: [],
    },
    {
      id: "EVT-7002",
      taskId: "TASK-1002",
      runId: "RUN-9002",
      timestamp: at(198),
      stage: "build",
      type: "info",
      severity: "low",
      message: "우선순위 함수 시그니처 업데이트",
      relatedFiles: ["scoring/priority.py", "task_generator/service.py"],
      relatedTests: ["tests/test_priority_scoring.py"],
    },
    {
      id: "EVT-7003",
      taskId: "TASK-1002",
      runId: "RUN-9002",
      timestamp: at(205),
      stage: "build",
      type: "retry",
      severity: "medium",
      message: "정적 분석 경고로 재시도 1회 수행",
      relatedFiles: ["task_generator/service.py"],
      relatedTests: ["ruff", "mypy"],
    },
    {
      id: "EVT-7004",
      taskId: "TASK-1003",
      runId: "RUN-9003",
      timestamp: at(295),
      stage: "review",
      type: "error",
      severity: "high",
      message: "라인 커버리지 80% 미만으로 품질 게이트 실패",
      relatedFiles: ["review_agent/policy.py"],
      relatedTests: ["pytest --cov"],
    },
    {
      id: "EVT-7005",
      taskId: "TASK-1004",
      runId: "RUN-9004",
      timestamp: at(428),
      stage: "ship",
      type: "info",
      severity: "low",
      message: "사용자 승인 대기 상태로 전환",
      relatedFiles: ["release/notes.md"],
      relatedTests: ["integration_release_check"],
    },
  ];

  const agents = [
    {
      id: "AGENT-1",
      name: "Hermes",
      status: "running",
      capabilities: ["orchestration", "task-planning", "dispatch"],
      successRate: 0.92,
      healthScore: 0.88,
      currentLoad: 4,
      lastActiveAt: at(430),
    },
    {
      id: "AGENT-2",
      name: "Codex",
      status: "running",
      capabilities: ["backend-coding", "frontend-coding", "review"],
      successRate: 0.89,
      healthScore: 0.91,
      currentLoad: 2,
      lastActiveAt: at(429),
    },
    {
      id: "AGENT-3",
      name: "OpenCode",
      status: "running",
      capabilities: ["local-modification", "test-fix"],
      successRate: 0.87,
      healthScore: 0.83,
      currentLoad: 3,
      lastActiveAt: at(420),
    },
    {
      id: "AGENT-4",
      name: "CodeRabbit",
      status: "degraded",
      capabilities: ["review", "quality-gate", "security-check"],
      successRate: 0.79,
      healthScore: 0.74,
      currentLoad: 1,
      lastActiveAt: at(305),
    },
  ];

  const prs = [
    {
      id: "PR-501",
      repository: "team/agent-ops",
      branch: "feature/knowledge-flow-graph",
      title: "feat: add knowledge flow graph endpoint + UI",
      status: "open",
      createdAt: at(410),
      mergedAt: null,
      associatedRuns: ["RUN-9004"],
      taskIds: ["TASK-1004"],
      summary: "연구-태스크-PR 링크를 대시보드에서 추적 가능하도록 개선",
      authorAgent: "Codex",
    },
    {
      id: "PR-498",
      repository: "team/agent-ops",
      branch: "fix/review-gate-policy",
      title: "fix: enforce coverage threshold by module",
      status: "review",
      createdAt: at(290),
      mergedAt: null,
      associatedRuns: ["RUN-9003"],
      taskIds: ["TASK-1003"],
      summary: "품질 게이트 기준을 모듈 단위로 적용",
      authorAgent: "CodeRabbit",
    },
    {
      id: "PR-490",
      repository: "team/agent-ops",
      branch: "feat/paper-parser-adapter",
      title: "feat: add parser adapter for OpenAlex metadata",
      status: "merged",
      createdAt: at(120),
      mergedAt: at(240),
      associatedRuns: ["RUN-8890"],
      taskIds: ["TASK-0991"],
      summary: "논문 메타데이터 추출 안정성 향상",
      authorAgent: "OpenCode",
    },
  ];

  const knowledgeArtifacts = [
    {
      id: "PAPER-100",
      title: "Adaptive Agent Orchestration in Multi-Agent Coding",
      summary:
        "멀티 에이전트 코딩 환경에서 오케스트레이션 정책이 생산성과 품질에 미치는 영향 분석",
      tags: ["orchestration", "agent-evaluation", "software-engineering"],
      confidence: 0.86,
      linkedTasks: ["TASK-1001"],
      linkedModules: ["backend/orchestrator"],
    },
    {
      id: "PAPER-101",
      title: "Priority Scoring for Autonomous Development Pipelines",
      summary: "태스크 우선순위 점수 계산을 위한 다목적 최적화 접근 제안",
      tags: ["prioritization", "optimization", "agent-pipeline"],
      confidence: 0.9,
      linkedTasks: ["TASK-1002"],
      linkedModules: ["backend/scoring"],
    },
    {
      id: "PAPER-102",
      title: "Traceable Knowledge Graphs for AI Coding Workflows",
      summary: "연구 산출물이 코드 변경과 PR까지 이어지는 과정을 그래프로 추적하는 방법",
      tags: ["knowledge-graph", "traceability", "visualization"],
      confidence: 0.84,
      linkedTasks: ["TASK-1004"],
      linkedModules: ["frontend/knowledge_flow", "backend/graph_api"],
    },
  ];

  return {
    tasks,
    runs,
    events,
    agents,
    prs,
    knowledgeArtifacts,
  };
}

module.exports = {
  makeSeedData,
};
